/**
 * 
 */
package com.ibm.au.optim.suro.couch.security;

/**
 * Interface <b>CouchDbSecurityEntity</b>. This interface defines the
 * set of common properties that are required by an instance that can
 * be inserted into <i>CouchDb</i>.
 * 
 * @author Christian Vecchiola
 */
public interface CouchDbSecurityEntity {
	
	/**
	 * A {@link String} constant that stores the name of the unique identifier property for
	 * <i>CouchDb</i> documents.
	 */
	static final String PROPERTY_COUCHDB_ID = "_id";
	
	/**
	 * A {@link String} constant that contains the name of the revision
	 * field of the document in the <i>CouchDb</i> database.
	 */
	static final String PROPERTY_REVISION	= "_rev";
	/**
	 * A {@link String} constant that contains the name of the identifier
	 * field. This it is not the unique identifier field in <i>CouchDb</i>
	 * but the one that stores the corresponding value in the {@link Map}
	 * implementation generated by the security entities.
	 */
	static final String PROPERTY_ID			= "id";
	/**
	 * A {@link String} constant representing the field that discriminates
	 * among the different types of security entities.
	 */
	static final String PROPERTY_TYPE		= "type";
	
	/**
	 * A {@link String} constant representing the field that discriminates
	 * all the security entities from other documents in the database.
	 */
	static final String PROPERTY_SECURITY 	= "cdbSecurity";
	
	/**
	 * A {@link String} constant that contains the information about the 
	 * version of the security entities.
	 */
	static final String SECURITY_VERSION	= "0.0.5";
	
	/**
	 * Gets the version revision of the entity.
	 * 
	 * @return	a {@link String} containing the identifier of the revision.
	 */
	String getRevision();
	
	/**
	 * Gets the value of the unique identifier of the entity.
	 * 
	 * @return	a {@link String} containing the value of the unique identifier.
	 */
	String getId();
	
	/**
	 * Gets the type of the security entity. This is the value of the 
	 * {@link CouchDbSecurityEntity#PROPERTY_TYPE} property.
	 * 
	 * @return	a {@link String}. 
	 */
	String getType();
	
}
