language: node_js
node_js:
  - "6.2.2"
before_install:
  - npm install -g eslint@3.4.0 eslint-config-airbnb@11.0.0 eslint-plugin-jsx-a11y@2.2.1 eslint-plugin-import@1.14.0 eslint-plugin-react@6.2.0 eslint-config-airbnb-base@7.0.0
  - eslint *
script: sh private/travis/deploy.sh
group: bluezone
branches:
  only:
    - master
    - production