package com.ibm.au.optim.suro.docloud;


import com.ibm.icu.text.SimpleDateFormat;

/**
 * Interface <b>Constants></b>. This class wraps a collection of
 * constant values that are used as defaults for initialising the
 * execution of a {@link Run} instance in DOCloud.
 */
public interface Constants {
    /**
     * Default accepted optimality, in percent
     */
    double DEFAULT_OPTIMALITY = 99.9; // percent

    /**
     * Default runtime for optimization jobs, in seconds
     */
    double DEFAULT_OPTIMIZATION_RUNTIME = 60.0; // seconds

    /**
     * Date formatter for use with the DOcloud Live Log API
     */
    SimpleDateFormat DOCLOUD_DATE_FORMATTER = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX");

    /**
     * A {@link String} constant that contains the name of the file that
     * contains the implementation of the optimisation model to run in
     * DOcloud.
     */
    String DOCLOUD_MODEL_FILE = "script.mod";

    /**
     * A {@link String} constant that contains the name of the file that
     * manages the runtime parameters (defaults) for the submission of the
     * optimisation runs.
     */
    String DOCLOUD_OPS_FILE = "model.ops";

    /**
     * A {@link String} constant that contains the name of the attachment
     * that will contain the log trace of the execution of the optimisation
     * in DOcloud.
     */
    String DOCLOUD_LOG_FILE = "log.txt";

    /**
     * A {@link String} constant that contains the MIME type of the log
     * file that is attached to the run and contains the log trace about
     * the execution of the run in DOcloud.
     */
    String DOCLOUD_LOG_MIME = "text/plain";

    /**
     * A {@link String} constant that contains the name of the attachment
     * that will contain the details of the solution generated by the
     * solver that executed the optimisation model.
     */
    String DOCLOUD_SOLUTION_FILE = "solution.json";

    /**
     * A {@link String} constant that contains the MIME type of the file
     * that will contain the solution details.
     */
    String DOCLOUD_SOLUTION_MIME = "application/json";


    /**
     * A {@link String} constant containing the name of the DOcloud specific
     * attribute that will contain the information about the interruption
     * status of a job.
     */
    String DOCLOUD_ATTRIBUTE_INTERRUPTION_TYPE = "docloud_interruptionType";
    /**
     * A {@link String} constant containing the name of the DOcloud specific
     * attribute that will contain the information about the class name of
     * the exception that interrupted the job in DOcloud.
     */
    String DOCLOUD_ATTRIBUTE_EXCEPTION_TYPE = "docloud_exceptionType";
    /**
     * A {@link String} constant containing the name of the DOcloud specific
     * attribute that will contain the message of the exception that interrupted
     * the job in DOcloud.
     */
    String DOCLOUD_ATTRIBUTE_EXCEPTION_MESSAGE = "docloud_exceptionMessage";
    /**
     * A {@link String} constant containing the name of the DOcloud specific
     * attribute that will contain the information about the type of failure
     * that occurred in DOcloud.
     */
    String DOCLOUD_ATTRIBUTE_FAILURE_TYPE = "docloud_failureType";
    /**
     * A {@link String} constant containing the name of the DOcloud specific
     * attribute that will contain the message of the failure that occurred
     * in DOcloud.
     */
    String DOCLOUD_ATTRIBUTE_FAILURE_MESSAGE = "docloud_failureMessage";

}